### ISSUE TITLE
Support private keys as the secret

### ISSUE THREAD

**Issue by ebeyrent** [mike-engel/jwt-cli#84] opened 2020-07-07 18:08 UTC
### Summary
For my application, I create a public and private key, and the public key is stored in my application.  
`openssl genrsa 3072 > ~/jwt.key.txt`
`openssl rsa -in ~/jwt.key.txt -pubout > ~/jwt.public.txt`

I need to use the private key as the secret, but when I attempt that, I get an invalid signature.

### Steps to reproduce
jwt encode -S '@jwt.key.txt' -e $(date -v+1H +%s) -P 'my_app={"uid": 20000006}' -k 20000006-1594139970

`jwt encode -S $(cat jwt.key.txt) -e $(date -v+1H +%s) -P 'drupal={"uid": 20000006}' -k 20000006-1594139970`
error: Found argument '--BEGIN' which wasn't expected, or isn't valid in this context

**Comment by mike-engel** [comment] 2020-07-08 07:36
As of right now, the code will only slurp files if the filename ends in `.pem`. Changing the extension of the private key to `.pem` should allow this to work as intended. Closing in favor of https://github.com/mike-engel/jwt-cli/issues/56#issuecomment-585978904, which requires a better solution than matching on the extension.

**Closed by mike-engel** 2020-07-08 07:36 UTC
