### ISSUE TITLE
Error: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by kimnh-0823** [mike-engel/jwt-cli#340] opened 2024-07-23 02:41 UTC
### Summary

```bash
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

### Steps to reproduce

1. Install CLI via brew:
```bash
brew install mike-engel/jwt-cli/jwt-cli
```

2. Get error message:
```bash
==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> Fetching mike-engel/jwt-cli/jwt-cli
==> Downloading https://github.com/mike-engel/jwt-cli/releases/download/6.1.0/jwt-linux.tar.gz
Already downloaded: /home/nguyen.huu.kim/.cache/Homebrew/downloads/c00ec111c05d4d919ea833d480a1baa44fbf95acb15d25ff14d8fa3418bb891b--jwt-linux.tar.gz
==> Installing jwt-cli from mike-engel/jwt-cli
/home/linuxbrew/.linuxbrew/Cellar/jwt-cli/6.1.0/bin/jwt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/linuxbrew/.linuxbrew/Cellar/jwt-cli/6.1.0/bin/jwt)
/home/linuxbrew/.linuxbrew/Cellar/jwt-cli/6.1.0/bin/jwt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/linuxbrew/.linuxbrew/Cellar/jwt-cli/6.1.0/bin/jwt)
/home/linuxbrew/.linuxbrew/Cellar/jwt-cli/6.1.0/bin/jwt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/linuxbrew/.linuxbrew/Cellar/jwt-cli/6.1.0/bin/jwt)
Error: Failure while executing; `\{\"SHELL\"=\>\"bash\"\} /home/linuxbrew/.linuxbrew/Cellar/jwt-cli/6.1.0/bin/jwt completion bash` exited with 1. Here's the output:
```

### Expected behavior

It should be installed successfully.

**Comment by mike-engel** [comment] 2024-08-21 20:58
Duplicate of #263 I think

**Closed by mike-engel** 2024-08-21 20:58 UTC
