### ISSUE TITLE
Add option to ignore alg type

### ISSUE THREAD

**Issue by OscBacon** [mike-engel/jwt-cli#341] opened 2024-07-24 15:01 UTC
### Summary
Hey, first off, amazing tool!

When using the firebase emulator, the jwt has `alg: "none"`
I would like the cli to still decode the jwt for debug purposes. Right now, I'm falling back to the debugger on jwt.io

### Steps to reproduce

Example jwt:
```
eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJhdWQiOiJodHRwczovL2lkZW50aXR5dG9vbGtpdC5nb29nbGVhcGlzLmNvbS9nb29nbGUuaWRlbnRpdHkuaWRlbnRpdHl0b29sa2l0LnYxLklkZW50aXR5VG9vbGtpdCIsImlhdCI6MTcyMTgzMjc1NywiZXhwIjoxNzIxODM2MzU3LCJpc3MiOiJmaXJlYmFzZS1hdXRoLWVtdWxhdG9yQGV4YW1wbGUuY29tIiwic3ViIjoiZmlyZWJhc2UtYXV0aC1lbXVsYXRvckBleGFtcGxlLmNvbSIsInVpZCI6InZCNDQ0WU9nZ21LWk5XVzZQQ0NRUTM2RTFQT2IiLCJjbGFpbXMiOnsiZG9tYWluIjoiaHR0cDovL2xvY2FsaG9zdDo1MTc0In19.
```

### Expected behavior
As per the jwt.io debugger:

Header
```
{
  "alg": "none",
  "typ": "JWT"
}
```

Payload
```
{
  "aud": "https://identitytoolkit.googleapis.com/google.identity.identitytoolkit.v1.IdentityToolkit",
  "iat": 1721832757,
  "exp": 1721836357,
  "iss": "firebase-auth-emulator@example.com",
  "sub": "firebase-auth-emulator@example.com",
  "uid": "vB444YOggmKZNWW6PCCQQ36E1POb",
  "claims": {
    "domain": "http://localhost:5174"
  }
}
```

**Comment by mike-engel** [comment] 2024-08-21 21:00
Hi @OscBacon, thanks for the suggestion! Unfortunately, it [doesn't look like `jsonwebtoken` will be supporting this](https://github.com/Keats/jsonwebtoken/issues/381), which would be required. I'll keep this open as a tracking issue

**Comment by mike-engel** [comment] 2024-08-21 21:52
Actually, I think this is a dupe of #253

**Closed by mike-engel** 2024-08-21 21:52 UTC
Labels: blocked
